<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AdminSettingsController;
use App\Http\Controllers\Api\AdminQuestionPaperController;
use App\Http\Controllers\Api\AdminExamCyclesController;
use App\Http\Controllers\Api\AdminSyllabusController;
use App\Http\Controllers\Api\AdminTimetableController;
use App\Http\Controllers\Api\CoreDataController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\ExamPortalController;
use App\Http\Controllers\Api\FeesController;
use App\Http\Controllers\Api\GalleryController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\ParentPortalController;
use App\Http\Controllers\Api\PromotionController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\PushNotificationController;
use App\Http\Controllers\Api\StudentHistoryController;
use App\Http\Controllers\Api\LeadsController;
use App\Http\Controllers\Api\MessagingController;
use App\Http\Controllers\Api\TeacherPortalController;
use App\Http\Controllers\Api\TeacherManagementController;
use App\Http\Controllers\Api\AcademicCalendarController;
use App\Http\Controllers\Api\BulkImportController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function (): void {
    Route::get('/admin-exists', [AuthController::class, 'adminExists']);
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/resolve-teacher-email', [AuthController::class, 'resolveTeacherEmail']);
    Route::post('/resolve-parent-email', [AuthController::class, 'resolveParentEmail']);
});

Route::middleware('api.token')->group(function (): void {
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::post('/auth/logout-everywhere', [AuthController::class, 'logoutEverywhere']);

    Route::get('/dashboard/stats', [DashboardController::class, 'stats']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::get('/notifications/stream', [NotificationController::class, 'stream']);
    Route::post('/notifications/mark-read', [NotificationController::class, 'markRead']);
    Route::post('/notifications/mark-all-read', [NotificationController::class, 'markAllRead']);
    Route::post('/notifications/delete-read', [NotificationController::class, 'deleteRead']);
    Route::delete('/notifications/{id}', [NotificationController::class, 'destroy']);
    Route::get('/notifications/push/vapid-key', [PushNotificationController::class, 'vapidKey'])->middleware('throttle:60,1');
    Route::post('/notifications/push/subscribe', [PushNotificationController::class, 'subscribe'])->middleware('throttle:30,1');
    Route::post('/notifications/push/unsubscribe', [PushNotificationController::class, 'unsubscribe'])->middleware('throttle:30,1');
    Route::get('/profile', [ProfileController::class, 'show']);
    Route::put('/profile', [ProfileController::class, 'update']);
    Route::post('/profile/photo', [ProfileController::class, 'uploadPhoto']);
    Route::put('/profile/password', [ProfileController::class, 'updatePassword']);

    Route::get('/classes', [CoreDataController::class, 'classes']);
    Route::get('/classes/management', [CoreDataController::class, 'classManagement']);
    Route::post('/classes', [CoreDataController::class, 'createClass']);
    Route::put('/classes/{id}', [CoreDataController::class, 'updateClass']);
    Route::delete('/classes/{id}', [CoreDataController::class, 'deleteClass']);
    Route::get('/attendance/report', [CoreDataController::class, 'attendanceReport']);
    Route::get('/subjects', [CoreDataController::class, 'subjects']);
    Route::post('/subjects', [CoreDataController::class, 'createSubject']);
    Route::put('/subjects/{id}', [CoreDataController::class, 'updateSubject']);
    Route::delete('/subjects/{id}', [CoreDataController::class, 'deleteSubject']);
    Route::get('/students', [CoreDataController::class, 'students']);
    Route::get('/students/directory', [CoreDataController::class, 'studentsDirectory']);
    Route::get('/students/history', [StudentHistoryController::class, 'show']);
    Route::get('/students/{id}/attendance-summary', [CoreDataController::class, 'studentAttendanceSummary']);
    Route::get('/students/{id}/exam-marks', [ExamPortalController::class, 'studentExamMarks']);
    Route::post('/promotion/execute', [PromotionController::class, 'execute']);
    Route::post('/promotion/execute-single', [PromotionController::class, 'executeSingle']);
    Route::get('/promotion/history', [PromotionController::class, 'history']);
    Route::post('/promotion/rollback', [PromotionController::class, 'rollback']);
    Route::post('/promotion/rollback-single', [PromotionController::class, 'rollbackSingle']);
    Route::get('/fees/management-data', [FeesController::class, 'managementData']);
    Route::post('/fees/class-students', [FeesController::class, 'classStudents']);
    Route::post('/fees/bulk-create', [FeesController::class, 'createBulk']);
    Route::post('/fees/import', [FeesController::class, 'importFees']);
    Route::put('/fees/{id}', [FeesController::class, 'update']);
    Route::post('/fees/delete-batch', [FeesController::class, 'deleteBatch']);
    Route::post('/fees/{id}/record-payment', [FeesController::class, 'recordPayment']);
    Route::post('/fees/payments', [FeesController::class, 'payments']);
    Route::get('/settings/receipt-template', [FeesController::class, 'getReceiptTemplate']);
    Route::put('/settings/receipt-template', [FeesController::class, 'saveReceiptTemplate']);
    Route::post('/settings/receipt-template/logo', [FeesController::class, 'uploadReceiptLogo']);
    Route::get('/settings/payment-gateway', [AdminSettingsController::class, 'paymentGateway']);
    Route::put('/settings/payment-gateway', [AdminSettingsController::class, 'updatePaymentGateway']);
    Route::post('/settings/invite-admin', [AdminSettingsController::class, 'inviteAdmin']);
    Route::post('/settings/factory-reset', [AdminSettingsController::class, 'factoryReset']);
    Route::post('/settings/full-reset', [AdminSettingsController::class, 'fullReset']);
    Route::get('/gallery/folders', [GalleryController::class, 'folders']);
    Route::post('/gallery/folders', [GalleryController::class, 'createFolder']);
    Route::put('/gallery/folders/{id}', [GalleryController::class, 'updateFolder']);
    Route::delete('/gallery/folders/{id}', [GalleryController::class, 'deleteFolder']);
    Route::get('/gallery/folders/{id}/images', [GalleryController::class, 'images']);
    Route::post('/gallery/folders/{id}/images', [GalleryController::class, 'uploadImage']);
    Route::put('/gallery/images/{id}', [GalleryController::class, 'updateImage']);
    Route::delete('/gallery/images/{id}', [GalleryController::class, 'deleteImage']);
    Route::get('/exams/{id}/marks-data', [ExamPortalController::class, 'examMarksData']);
    Route::put('/exams/{id}/marks', [ExamPortalController::class, 'saveExamMarks']);
    Route::post('/exams/{id}/marks/import', [ExamPortalController::class, 'importExamMarks']);
    Route::get('/weekly-exams/{id}/marks-data', [ExamPortalController::class, 'weeklyExamMarksData']);
    Route::put('/weekly-exams/{id}/marks', [ExamPortalController::class, 'saveWeeklyExamMarks']);
    Route::get('/messaging/classes', [MessagingController::class, 'classes'])->middleware('throttle:120,1');
    Route::get('/messaging/teachers', [MessagingController::class, 'teachers'])->middleware('throttle:120,1');
    Route::get('/messaging/admin-user', [MessagingController::class, 'adminUser'])->middleware('throttle:120,1');
    Route::get('/messaging/students/class/{classId}', [MessagingController::class, 'studentsByClass'])->middleware('throttle:120,1');
    Route::get('/messaging/contacts', [MessagingController::class, 'contacts'])->middleware('throttle:120,1');
    Route::get('/messaging/messages', [MessagingController::class, 'messages'])->middleware('throttle:180,1');
    Route::post('/messaging/messages', [MessagingController::class, 'send'])->middleware('throttle:40,1');
    Route::put('/messaging/messages/{id}/read', [MessagingController::class, 'markRead'])->middleware('throttle:120,1');
    Route::get('/teachers', [CoreDataController::class, 'teachers']);
    Route::get('/teachers/basic', [CoreDataController::class, 'teachersBasic']);
    Route::get('/admin/timetable/management-data', [AdminTimetableController::class, 'managementData']);
    Route::get('/admin/timetable/class/{classId}', [AdminTimetableController::class, 'classTimetable']);
    Route::get('/admin/timetable/teacher/{teacherId}', [AdminTimetableController::class, 'teacherSchedule']);
    Route::get('/admin/timetable/periods', [AdminTimetableController::class, 'indexPeriods']);
    Route::post('/admin/timetable/periods', [AdminTimetableController::class, 'storePeriod']);
    Route::put('/admin/timetable/periods/{id}', [AdminTimetableController::class, 'updatePeriod']);
    Route::delete('/admin/timetable/periods/{id}', [AdminTimetableController::class, 'destroyPeriod']);
    Route::post('/admin/timetable', [AdminTimetableController::class, 'store']);
    Route::put('/admin/timetable/publish-class', [AdminTimetableController::class, 'publishClass']);
    Route::put('/admin/timetable/{id}', [AdminTimetableController::class, 'update']);
    Route::delete('/admin/timetable/{id}', [AdminTimetableController::class, 'destroy']);
    Route::put('/admin/timetable/{id}/publish', [AdminTimetableController::class, 'togglePublish']);
    
    // Timetable Schedule Configuration (accessible to all roles)
    Route::get('/timetable/schedule-config', [App\Http\Controllers\Api\TimetableScheduleConfigController::class, 'index']);
    Route::post('/admin/timetable/schedule-config', [App\Http\Controllers\Api\TimetableScheduleConfigController::class, 'store']);
    Route::post('/admin/timetable/schedule-config/reset', [App\Http\Controllers\Api\TimetableScheduleConfigController::class, 'reset']);
    Route::get('/admin/syllabus/data', [AdminSyllabusController::class, 'data']);
    Route::post('/admin/syllabus', [AdminSyllabusController::class, 'store']);
    Route::post('/admin/syllabus/bulk', [AdminSyllabusController::class, 'bulkStore']);
    Route::post('/admin/syllabus/import', [AdminSyllabusController::class, 'import']);
    Route::put('/admin/syllabus/{id}', [AdminSyllabusController::class, 'update']);
    Route::delete('/admin/syllabus/{id}', [AdminSyllabusController::class, 'destroy']);
    Route::post('/admin/syllabus/{id}/teachers', [AdminSyllabusController::class, 'assignTeacher']);
    Route::delete('/admin/syllabus/teachers/{id}', [AdminSyllabusController::class, 'removeTeacherMapping']);
    Route::get('/admin/question-papers/data', [AdminQuestionPaperController::class, 'data']);
    Route::get('/admin/question-papers/{id}/questions', [AdminQuestionPaperController::class, 'questions']);
    Route::post('/admin/question-papers', [AdminQuestionPaperController::class, 'storePaper']);
    Route::delete('/admin/question-papers/{id}', [AdminQuestionPaperController::class, 'deletePaper']);
    Route::post('/admin/question-papers/{id}/questions', [AdminQuestionPaperController::class, 'storeQuestion']);
    Route::put('/admin/questions/{id}', [AdminQuestionPaperController::class, 'updateQuestion']);
    Route::delete('/admin/questions/{id}', [AdminQuestionPaperController::class, 'deleteQuestion']);
    Route::get('/admin/exam-cycles', [AdminExamCyclesController::class, 'index']);
    Route::post('/admin/exam-cycles', [AdminExamCyclesController::class, 'store']);
    Route::put('/admin/exam-cycles/{id}/toggle-active', [AdminExamCyclesController::class, 'toggleActive']);
    Route::delete('/admin/exam-cycles/{id}', [AdminExamCyclesController::class, 'destroy']);
    Route::post('/admin/students', [TeacherPortalController::class, 'createStudent']);
    Route::get('/teacher/classes', [TeacherPortalController::class, 'classes']);
    Route::get('/teacher/dashboard', [TeacherPortalController::class, 'dashboard']);
    Route::get('/teacher/attendance-data', [TeacherPortalController::class, 'attendanceData']);
    Route::put('/teacher/attendance', [TeacherPortalController::class, 'saveAttendance']);
    Route::get('/teacher/students-data', [TeacherPortalController::class, 'studentsData']);
    Route::post('/teacher/students', [TeacherPortalController::class, 'createStudent']);
    Route::put('/teacher/students/{id}', [TeacherPortalController::class, 'updateStudent']);
    Route::delete('/teacher/students/{id}', [TeacherPortalController::class, 'destroyStudent']);
    Route::get('/teacher/leave-requests', [TeacherPortalController::class, 'leaveRequests']);
    Route::post('/teacher/leave-requests', [TeacherPortalController::class, 'createLeaveRequest']);
    Route::get('/teacher/timetable-data', [TeacherPortalController::class, 'timetableData']);
    Route::get('/teacher/homework-data', [TeacherPortalController::class, 'homeworkData']);
    Route::post('/teacher/homework', [TeacherPortalController::class, 'createHomework']);
    Route::delete('/teacher/homework/{id}', [TeacherPortalController::class, 'deleteHomework']);
    Route::get('/teacher/weekly-exams-data', [TeacherPortalController::class, 'weeklyExamsData']);
    Route::get('/teacher/reports-data', [TeacherPortalController::class, 'reportsData']);
    Route::get('/teacher/class-students', [TeacherPortalController::class, 'classStudents']);
    Route::post('/teacher/reports', [TeacherPortalController::class, 'createReport']);
    Route::put('/teacher/complaints/{id}', [TeacherPortalController::class, 'updateTeacherComplaint']);
    Route::get('/teacher/syllabus-data', [TeacherPortalController::class, 'syllabusData']);
    Route::put('/teacher/syllabus/{id}/complete', [TeacherPortalController::class, 'markSyllabusCompleted']);
    Route::get('/teacher/exams-data', [ExamPortalController::class, 'teacherExamsData']);
    Route::get('/parent/dashboard', [ParentPortalController::class, 'dashboard']);
    Route::get('/parent/exams-data', [ParentPortalController::class, 'exams']);
    Route::get('/parent/certificate-requests', [ParentPortalController::class, 'certificateRequests']);
    Route::post('/parent/certificate-requests', [ParentPortalController::class, 'createCertificateRequest']);
    Route::get('/parent/leave-requests', [ParentPortalController::class, 'leaveRequests']);
    Route::post('/parent/leave-requests', [ParentPortalController::class, 'createLeaveRequest']);
    Route::get('/parent/attendance-data', [ParentPortalController::class, 'attendance']);
    Route::get('/parent/timetable-data', [ParentPortalController::class, 'timetable']);
    Route::get('/parent/syllabus-data', [ParentPortalController::class, 'syllabus']);
    Route::get('/parent/fees-data', [ParentPortalController::class, 'fees']);
    Route::get('/parent/fees/payment-gateway-config', [ParentPortalController::class, 'paymentGatewayConfig']);
    Route::post('/parent/fees/{id}/create-order', [ParentPortalController::class, 'createFeePaymentOrder']);
    Route::post('/parent/fees/{id}/verify-payment', [ParentPortalController::class, 'verifyFeePayment']);
    Route::post('/parent/fees/{id}/pay', [ParentPortalController::class, 'payFee']);
    Route::get('/parent/children-data', [ParentPortalController::class, 'children']);
    Route::get('/parent/complaints', [ParentPortalController::class, 'complaints']);
    Route::post('/parent/complaints', [ParentPortalController::class, 'createComplaint']);
    Route::get('/parent/homework-data', [ParentPortalController::class, 'homework']);
    Route::get('/parent/progress-data', [ParentPortalController::class, 'progress']);
    Route::get('/teachers/management', [TeacherManagementController::class, 'index']);
    Route::post('/teachers', [TeacherManagementController::class, 'store']);
    Route::post('/teachers/management/import', [BulkImportController::class, 'teachers']);
    Route::post('/admin/students/import', [BulkImportController::class, 'students']);
    Route::put('/admin/students/{id}', [TeacherPortalController::class, 'updateStudent']);
    Route::delete('/admin/students/{id}', [TeacherPortalController::class, 'destroyStudent']);
    Route::put('/teachers/{id}', [TeacherManagementController::class, 'update']);
    Route::delete('/teachers/{id}', [TeacherManagementController::class, 'destroy']);
    Route::get('/parents', [CoreDataController::class, 'parents']);

    Route::get('/announcements', [CoreDataController::class, 'announcements']);
    Route::post('/announcements', [CoreDataController::class, 'createAnnouncement']);
    Route::delete('/announcements/{id}', [CoreDataController::class, 'deleteAnnouncement']);

    Route::get('/complaints/management', [CoreDataController::class, 'complaintsManagement']);
    Route::put('/complaints/{id}', [CoreDataController::class, 'updateComplaint']);

    Route::get('/certificates/requests', [CoreDataController::class, 'certificateRequests']);
    Route::put('/certificates/requests/{id}', [CoreDataController::class, 'updateCertificateRequest']);

    Route::get('/leave/requests', [CoreDataController::class, 'leaveRequests']);
    Route::put('/leave/requests/{id}', [CoreDataController::class, 'updateLeaveRequest']);

    Route::get('/exams/data', [ExamPortalController::class, 'examsData']);
    Route::get('/exams/results-data', [ExamPortalController::class, 'examResultsData']);
    Route::post('/exams/bulk', [ExamPortalController::class, 'createExamsBulk']);
    Route::delete('/exams/{id}', [ExamPortalController::class, 'deleteExam']);

    Route::get('/weekly-exams/data', [ExamPortalController::class, 'weeklyData']);
    Route::post('/weekly-exams', [ExamPortalController::class, 'createWeekly']);
    Route::put('/weekly-exams/{id}', [ExamPortalController::class, 'updateWeekly']);
    Route::put('/weekly-exams/{id}/status', [ExamPortalController::class, 'updateWeeklyStatus']);
    Route::put('/weekly-exams/{id}/syllabus-links', [ExamPortalController::class, 'saveWeeklySyllabus']);
    Route::delete('/weekly-exams/{id}', [ExamPortalController::class, 'deleteWeekly']);

    Route::get('/leads', [LeadsController::class, 'index']);
    Route::post('/leads', [LeadsController::class, 'store']);
    Route::post('/leads/import', [LeadsController::class, 'import']);
    Route::get('/leads/teachers', [LeadsController::class, 'teachers']);
    Route::get('/leads/module-status', [LeadsController::class, 'moduleStatus']);
    Route::get('/leads/settings', [LeadsController::class, 'settings']);
    Route::put('/leads/settings/module', [LeadsController::class, 'updateModule']);
    Route::put('/leads/settings/mode', [LeadsController::class, 'updateMode']);
    Route::put('/leads/settings/teacher/{teacherId}', [LeadsController::class, 'updateTeacherPermission']);
    Route::get('/leads/{id}/details', [LeadsController::class, 'details']);
    Route::post('/leads/{id}/call-logs', [LeadsController::class, 'addCallLog']);
    Route::put('/leads/{id}/status', [LeadsController::class, 'updateStatus']);
    Route::put('/leads/{id}', [LeadsController::class, 'update']);
    Route::delete('/leads/{id}', [LeadsController::class, 'destroy']);

    Route::get('/academic-calendar', [AcademicCalendarController::class, 'index']);
    Route::get('/academic-calendar/audience-users', [AcademicCalendarController::class, 'audienceUsers']);
    Route::get('/academic-calendar/{id}', [AcademicCalendarController::class, 'show']);
    Route::post('/academic-calendar', [AcademicCalendarController::class, 'store']);
    Route::put('/academic-calendar/{id}', [AcademicCalendarController::class, 'update']);
    Route::delete('/academic-calendar/{id}', [AcademicCalendarController::class, 'destroy']);

    Route::get('/holidays', [AcademicCalendarController::class, 'index']);
    Route::post('/holidays', [AcademicCalendarController::class, 'store']);
    Route::put('/holidays/{id}', [AcademicCalendarController::class, 'update']);
    Route::delete('/holidays/{id}', [AcademicCalendarController::class, 'destroy']);
});
