import {
  Users,
  GraduationCap,
  BookOpen,
  Calendar,
  Bell,
  FileText,
  CreditCard,
  MessageSquare,
  Settings,
  Shield,
  Clock,
  LayoutDashboard,
  Library,
  Award,
  UserPlus,
  Image,
  CalendarDays,
  TrendingUp,
  History,
} from 'lucide-react';

export const adminSidebarItems = [
  { icon: <LayoutDashboard className="h-5 w-5" />, label: 'Dashboard', path: '/admin' },
  { icon: <Users className="h-5 w-5" />, label: 'Teachers', path: '/admin/teachers' },
  { icon: <GraduationCap className="h-5 w-5" />, label: 'Students', path: '/admin/students' },
  { icon: <History className="h-5 w-5" />, label: 'Student History', path: '/admin/student-history' },
  { icon: <TrendingUp className="h-5 w-5" />, label: 'Promotion', path: '/admin/promotion' },
  { icon: <BookOpen className="h-5 w-5" />, label: 'Classes', path: '/admin/classes' },
  { icon: <Library className="h-5 w-5" />, label: 'Subjects', path: '/admin/subjects' },
  { icon: <Calendar className="h-5 w-5" />, label: 'Timetable', path: '/admin/timetable' },
  { icon: <Clock className="h-5 w-5" />, label: 'Attendance', path: '/admin/attendance' },
  { icon: <FileText className="h-5 w-5" />, label: 'Exams', path: '/admin/exams' },
  { icon: <BookOpen className="h-5 w-5" />, label: 'Syllabus', path: '/admin/syllabus' },

  { icon: <UserPlus className="h-5 w-5" />, label: 'Leads', path: '/admin/leads' },
  { icon: <Bell className="h-5 w-5" />, label: 'Announcements', path: '/admin/announcements' },
  { icon: <Shield className="h-5 w-5" />, label: 'Leave Requests', path: '/admin/leave' },
  { icon: <Award className="h-5 w-5" />, label: 'Certificates', path: '/admin/certificates' },
  { icon: <MessageSquare className="h-5 w-5" />, label: 'Complaints', path: '/admin/complaints' },
  { icon: <CreditCard className="h-5 w-5" />, label: 'Fees', path: '/admin/fees' },
  { icon: <Image className="h-5 w-5" />, label: 'Gallery', path: '/admin/gallery' },
  { icon: <CalendarDays className="h-5 w-5" />, label: 'Academic Calendar', path: '/admin/academic-calendar' },
  { icon: <Bell className="h-5 w-5" />, label: 'Notifications', path: '/admin/notifications' },
  { icon: <MessageSquare className="h-5 w-5" />, label: 'Messages', path: '/admin/messages' },
  { icon: <Settings className="h-5 w-5" />, label: 'Settings', path: '/admin/settings' },
];
