import {
  LayoutDashboard,
  User,
  Clock,
  Calendar,
  BookOpen,
  FileText,
  TrendingUp,
  Bell,
  MessageSquare,
  Award,
  CreditCard,
  Image,
  LibraryBig,
  Settings,
  AlertTriangle,
  CalendarDays,
} from 'lucide-react';

export const parentSidebarItems = [
  { icon: <LayoutDashboard className="h-5 w-5" />, label: 'Dashboard', path: '/parent' },
  { icon: <User className="h-5 w-5" />, label: 'My Child', path: '/parent/child' },
  { icon: <Clock className="h-5 w-5" />, label: 'Attendance', path: '/parent/attendance' },
  { icon: <Calendar className="h-5 w-5" />, label: 'Timetable', path: '/parent/timetable' },
  { icon: <BookOpen className="h-5 w-5" />, label: 'Homework', path: '/parent/homework' },
  { icon: <LibraryBig className="h-5 w-5" />, label: 'Syllabus', path: '/parent/syllabus' },
  { icon: <FileText className="h-5 w-5" />, label: 'Exam Results', path: '/parent/exams' },
  { icon: <TrendingUp className="h-5 w-5" />, label: 'Progress', path: '/parent/progress' },
  { icon: <Bell className="h-5 w-5" />, label: 'Announcements', path: '/parent/announcements' },
  { icon: <Calendar className="h-5 w-5" />, label: 'Leave Request', path: '/parent/leave' },
  { icon: <AlertTriangle className="h-5 w-5" />, label: 'Complaints', path: '/parent/complaints' },
  { icon: <Bell className="h-5 w-5" />, label: 'Notifications', path: '/parent/notifications' },
  { icon: <MessageSquare className="h-5 w-5" />, label: 'Messages', path: '/parent/messages' },
  { icon: <Award className="h-5 w-5" />, label: 'Certificates', path: '/parent/certificates' },
  { icon: <Image className="h-5 w-5" />, label: 'Gallery', path: '/parent/gallery' },
  { icon: <CalendarDays className="h-5 w-5" />, label: 'Academic Calendar', path: '/parent/academic-calendar' },
  { icon: <CreditCard className="h-5 w-5" />, label: 'Pay Fees', path: '/parent/fees' },
  { icon: <Settings className="h-5 w-5" />, label: 'Settings', path: '/parent/settings' },
];
